pipeline {
    agent any

    stages {
        stage('Environment Check') {
            steps {
                sh 'node -v'
                sh 'npm -v'
                sh 'docker --version'
                sh 'git --version'
            }
        }
    }
}
