pipeline {
agent any

environment {
    DOCKER_HUB_USER = "srinidhisanjeevi"

    BACKEND_IMAGE = "${DOCKER_HUB_USER}/auth-backend:${params.IMAGE_TAG}"
    FRONTEND_IMAGE = "${DOCKER_HUB_USER}/auth-frontend:${params.IMAGE_TAG}"
}

stages {

stage('Checkout Code') {
    steps {
        echo 'Downloading latest source code from GitHub'
        checkout scm
    }
}

stage('Environment Validation') {
    steps {
        sh 'node -v'
        sh 'npm -v'
        sh 'docker --version'
        sh 'git --version'
    }
}

stage('Install Backend Dependencies') {
    steps {
        dir('L04/docker_project/backend') {
            sh 'npm install'
        }
    }
}
    
stage('Show Parameters') {
    steps {
        echo "Selected Tag: ${params.IMAGE_TAG}"
    }
}



stage('Verify Project Files') {
    steps {
        sh 'ls -la L04/docker_project/backend'
        sh 'ls -la L04/docker_project/frontend'
    }
}

stage('Build Images') {

    parallel {

        stage('Backend Build') {
            steps {
                echo 'Building Backend Image'

                sh """
                docker build \
                -t ${DOCKER_HUB_USER}/auth-backend:${params.IMAGE_TAG} \
                L04/docker_project/backend
                """
            }
        }

        stage('Frontend Build') {
            steps {
                echo 'Building Frontend Image'

                sh """
                docker build \
                -t ${DOCKER_HUB_USER}/auth-frontend:${params.IMAGE_TAG} \
                L04/docker_project/frontend
                """
            }
        }
    }
}
    
stage('Verify Docker Images') {
    steps {
        sh 'docker images | grep srinidhisanjeevi'
    }
}

stage('Docker Hub Login') {
    steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'dockerhub-creds',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )
        ]) {
            sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            '''
        }
    }
}
stage('Push Backend Image') {
    steps {
        sh "docker push ${DOCKER_HUB_USER}/auth-backend:${params.IMAGE_TAG}"
    }
}

stage('Push Frontend Image') {
    steps {
        sh "docker push ${DOCKER_HUB_USER}/auth-frontend:${params.IMAGE_TAG}"
    }
}
    
}

post {

success {
    echo 'Pipeline completed successfully'
}

failure {
    echo 'Pipeline failed'
}

always {
    sh 'docker logout || true'
    echo 'Pipeline execution finished'
}

}

}
